server.port=8081

# ========================= BASE DE DATOS =========================
spring.datasource.url=jdbc:mysql://localhost:3306/db_clasificator?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Cc30333704

# ========================= CONNECTION POOL ( Permite manejar el trafico de request de nuestra nase de datos) =========================
spring.datasource.hikari.maximum-pool-size=10
@@ -23,4 +23,7 @@ logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO

#========================= JPA / HIBERNATE =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ========================= OTHER MS ==========================
ms.security.url=http://localhost:8080
spring.profiles.active=dev

default.role.patient = 6a0b6a301041bc61dc39cbf5
default.role.doctor = 6a0b69f11041bc61dc39cbf4

ms.secret.key = ComunicacionEntreMicroservicios123.