# ========================= SERVIDOR =========================
server.port=8081

# ========================= BASE DE DATOS =========================
spring.datasource.url=jdbc:mysql://localhost:3306/db-clasificator?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=jacobo123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================= CONNECTION POOL ( Permite manejar el trafico de request de nuestra nase de datos) =========================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# ========================= JPA / HIBERNATE =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ========================= LOGGING =========================
logging.level.org.springframework.boot=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO
